# Generated by Django 6.0.6 on 2026-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactlead_jobapplication_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='conteudo',
            field=models.TextField(help_text='Conteúdo completo do post (exibido na página do post).'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='imagem_destaque',
            field=models.ImageField(blank=True, help_text='Imagem exibida no card do blog.', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='resumo',
            field=models.TextField(blank=True, help_text='Texto curto exibido no card do blog.', max_length=300),
        ),
    ]
