# Generated by Django 6.0.6 on 2026-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_postblog_conteudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da especialidade (ex: Iniciativa Pública)', max_length=200)),
                ('imagem', models.ImageField(help_text='Imagem de fundo da especialidade', upload_to='especialidades/')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)')),
                ('ativo', models.BooleanField(default=True, help_text='Exibir esta especialidade no site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
