# Generated by Django 6.0.6 on 2026-08-04

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Especialidade = apps.get_model('core', 'Especialidade')
    for esp in Especialidade.objects.all():
        base = slugify(esp.titulo)
        slug = base
        n = 2
        while Especialidade.objects.exclude(pk=esp.pk).filter(slug=slug).exists():
            slug = f"{base}-{n}"
            n += 1
        esp.slug = slug
        esp.save()


def reverse_slugs(apps, schema_editor):
    Especialidade = apps.get_model('core', 'Especialidade')
    Especialidade.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da especialidade, exibida na página de detalhe no site'),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='slug',
            # db_index=False: evita que o AddField agende a index "_like" (e a
            # btree) no final da migração; o AlterField(unique=True) abaixo as
            # recria corretamente. Sem isso, o Postgres falha criando a index
            # "core_especialidade_slug_a26f1f77_like" duas vezes.
            field=models.SlugField(help_text='Identificador usado na URL da página da especialidade (ex: iniciativa-publica)', null=True, db_index=False),
        ),
        migrations.RunPython(backfill_slugs, reverse_slugs),
        migrations.AlterField(
            model_name='especialidade',
            name='slug',
            field=models.SlugField(help_text='Identificador usado na URL da página da especialidade (ex: iniciativa-publica)', unique=True),
        ),
    ]
