# Generated by Django 6.0.6 on 2026-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_especialidade_slug_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail do cliente', max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, help_text='Nome do cliente (opcional)', max_length=200)),
                ('origem', models.CharField(choices=[('eventos', 'Eventos'), ('contato', 'Contato'), ('footer', 'Footer')], default='footer', max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Assinatura ativa (não cancelada)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição de Newsletter',
                'verbose_name_plural': 'Inscrições de Newsletter',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
