# Generated by Django 6.0.6 on 2026-08-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsletterinscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('primeira_visita', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_por_ip', to='core.postblog')),
            ],
            options={
                'verbose_name': 'Visualização de Post',
                'verbose_name_plural': 'Visualizações de Post',
                'ordering': ['-primeira_visita'],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
