# Generated by Django 6.0.6 on 2026-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postvisualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='mensagem',
            field=models.TextField(blank=True, help_text='Mensagem opcional enviada pelo visitante'),
        ),
    ]
