# Generated by Django 6.0.6 on 2026-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactlead_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Candidatura', 'verbose_name_plural': 'Trabalhe Conosco'},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='preview',
            field=models.ImageField(blank=True, help_text='Imagem da primeira página do currículo (gerada automaticamente para PDFs).', null=True, upload_to='curriculos/previews/'),
        ),
    ]
