# Generated by Django 6.0.6 on 2026-08-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_jobapplication_options_jobapplication_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterinscricao',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular do cliente (opcional)', max_length=30),
        ),
        migrations.AlterField(
            model_name='newsletterinscricao',
            name='origem',
            field=models.CharField(choices=[('eventos', 'Eventos'), ('contato', 'Contato'), ('footer', 'Footer'), ('blog', 'Blog')], default='footer', max_length=20),
        ),
    ]
