# Generated by Django 6.0.6 on 2026-08-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_newsletterinscricao_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título interno para identificar a imagem (opcional)', max_length=200)),
                ('imagem', models.ImageField(help_text='Imagem do carrossel (recomendado: 1950x700)', upload_to='carrossel/')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)')),
                ('ativo', models.BooleanField(default=True, help_text='Exibir esta imagem no carrossel do site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem do Carrossel',
                'verbose_name_plural': 'Carrossel',
                'ordering': ['ordem', 'data_criacao'],
            },
        ),
    ]
