# Generated by Django 6.0.6 on 2026-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carrossel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='botao1_link',
            field=models.CharField(blank=True, help_text='Para "página interna": use sobre, solucoes, eventos, especialidades, blog ou home. Para "link externo": cole a URL completa (ex.: https://calendly.com/...)', max_length=500),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='botao1_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 1 (ex.: Agende sua Reunião)', max_length=60),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='botao1_tipo',
            field=models.CharField(choices=[('nenhum', 'Nenhum (não exibir botão)'), ('whatsapp', 'Abrir modal de WhatsApp'), ('contato', 'Ir para a página de Contato'), ('pagina', 'Ir para uma página interna'), ('externo', 'Abrir link externo (nova aba)')], default='nenhum', help_text='O que o botão 1 faz ao ser clicado', max_length=20),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='botao2_link',
            field=models.CharField(blank=True, help_text='Para "página interna": use sobre, solucoes, eventos, especialidades, blog ou home. Para "link externo": cole a URL completa', max_length=500),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='botao2_texto',
            field=models.CharField(blank=True, help_text='Texto do botão 2 (ex.: Fale conosco)', max_length=60),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='botao2_tipo',
            field=models.CharField(choices=[('nenhum', 'Nenhum (não exibir botão)'), ('whatsapp', 'Abrir modal de WhatsApp'), ('contato', 'Ir para a página de Contato'), ('pagina', 'Ir para uma página interna'), ('externo', 'Abrir link externo (nova aba)')], default='nenhum', help_text='O que o botão 2 faz ao ser clicado', max_length=20),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Texto de apoio exibido abaixo do título (opcional)', max_length=300),
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título exibido sobre a imagem (opcional)', max_length=200),
        ),
    ]
