# Generated by Django 6.0.6 on 2026-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carrossel_botao1_link_carrossel_botao1_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de pessoa exibida ao lado do texto, sem imagem de fundo (opcional)', null=True, upload_to='carrossel/pessoas/'),
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de fundo do carrossel (recomendado: 1950x700). Opcional se houver foto de pessoa.', null=True, upload_to='carrossel/'),
        ),
    ]
