# Generated by Django 6.0.6 on 2026-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carrossel_foto_alter_carrossel_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNosFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Legenda da foto, exibida como texto alternativo (opcional)', max_length=200)),
                ('imagem', models.ImageField(help_text='Imagem exibida no carrossel 3D da seção Sobre Nós (recomendado: proporção retrato)', upload_to='sobrenos/')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)')),
                ('ativo', models.BooleanField(default=True, help_text='Exibir esta foto na seção Sobre Nós do site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto Sobre Nós',
                'verbose_name_plural': 'Sobre Nós Fotos',
                'ordering': ['ordem', 'data_criacao'],
            },
        ),
    ]
