# Generated by Django 6.0.6 on 2026-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sobrenosfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='interesse',
            field=models.CharField(choices=[('geral', 'Só entrar em contato'), ('abrir_empresa', 'Abertura de Empresa'), ('migracao_contabilidade', 'Migração de Contabilidade'), ('migracao_mei_me', 'Migração de MEI para ME'), ('declaracao_irpf', 'Declaração IRPF')], default='geral', help_text='Interesse principal do visitante', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='origem',
            field=models.CharField(choices=[('site', 'Site (legado)'), ('home_form', 'Formulário da Home'), ('pagina_contato', 'Página de Contato'), ('blog_lead', 'Lead do Blog'), ('whatsapp_modal', 'Modal de WhatsApp'), ('whatsapp_direto', 'WhatsApp direto (clique)')], default='site', help_text='De onde veio o contato (formulário, página, clique em WhatsApp, etc.)', max_length=50),
        ),
    ]
