# Generated by Django 6.0.6 on 2026-08-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contactlead_interesse_alter_contactlead_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, help_text='CPF do cliente (opcional)', max_length=14, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ do cliente (opcional)', max_length=20)),
                ('auth_token', models.CharField(blank=True, help_text='Token de sessão gerado no login', max_length=64, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='contactlead',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF informado pelo visitante (opcional)', max_length=14),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='origem',
            field=models.CharField(choices=[('site', 'Site (legado)'), ('home_form', 'Formulário da Home'), ('pagina_contato', 'Página de Contato'), ('blog_lead', 'Lead do Blog'), ('whatsapp_modal', 'Modal de WhatsApp'), ('whatsapp_direto', 'WhatsApp direto (clique)'), ('solucoes', 'Soluções (logado)')], default='site', help_text='De onde veio o contato (formulário, página, clique em WhatsApp, etc.)', max_length=50),
        ),
    ]
