# Generated by Django 6.0.6 on 2026-08-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cliente_contactlead_cpf_alter_contactlead_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Admin'), ('social_media', 'Social Media'), ('rh', 'RH'), ('comercial', 'Comercial'), ('editor', 'Editor (legado)'), ('moderador', 'Moderador (legado)')], default='moderador', max_length=20),
        ),
    ]
