# Generated by Django 6.0.6 on 2026-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_criar_grupos_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSuspeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], default=2, help_text='Gravidade estimada do comportamento')),
                ('motivo', models.TextField(blank=True, help_text='Por que este IP foi marcado (preenchido automaticamente; pode ser editado)')),
                ('resolvido', models.BooleanField(db_index=True, default=False, help_text='Marque quando o acesso for investigado e deixar de ser uma ameaça')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_visto', models.DateTimeField(auto_now=True, help_text='Última vez que este IP teve atividade flagrada')),
            ],
            options={
                'verbose_name': 'IP Suspeito',
                'verbose_name_plural': 'IPs Suspeitos',
                'ordering': ['-resolvido', '-ultima_visto'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('request_rate', 'Muitas requisições'), ('path_invasivo', 'Path de ataque/scanner'), ('user_agent_suspeito', 'User-Agent suspeito'), ('injecao', 'Tentativa de injeção'), ('honeypot', 'Bot detectado (honeypot)'), ('falha_recaptcha', 'Falha no reCAPTCHA'), ('rate_limit', 'Limite de contato excedido'), ('upload_invalido', 'Upload inválido'), ('login_admin', 'Acesso ao admin (sem permissão)'), ('outro', 'Outro')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('detalhes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento de Segurança',
                'verbose_name_plural': 'Eventos de Segurança',
                'ordering': ['-timestamp'],
            },
        ),
    ]
