# Generated by Django 6.0.6 on 2026-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ipsuspeito_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='origem',
            field=models.CharField(choices=[('site', 'Site (legado)'), ('home_form', 'Formulário da Home'), ('pagina_contato', 'Página de Contato'), ('blog_lead', 'Lead do Blog'), ('whatsapp_modal', 'Modal de WhatsApp'), ('whatsapp_direto', 'WhatsApp direto (clique)'), ('solucoes', 'Soluções (logado)'), ('academy_business', 'Academy Business')], default='site', help_text='De onde veio o contato (formulário, página, clique em WhatsApp, etc.)', max_length=50),
        ),
    ]
