# Generated by Django 6.0.6 on 2026-08-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_contactlead_origem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPSuspeito',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
    ]
