# Generated by Django 6.0.6 on 2026-09-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_ipsuspeito_delete_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Autor do post. Ao excluir o usuário, o post é mantido (autor fica vazio).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
