# Generated by Django 6.0.6 on 2026-09-10 12:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_postblog_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Conteúdo completo do post com formatação rica (editor WYSIWYG). Exibido na página do post.', verbose_name='Conteúdo'),
        ),
    ]
