"""
Django settings for orcoma_admin project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega as variáveis do arquivo .env (credenciais nunca ficam no código)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY' , 'django-insecure-8j&-$s%%urrrg4$36+ul9vi3ie63=ci1y%6@e36#+3a2thtmjb' )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS: o frontend (Vercel) chama a API (Render) diretamente via VITE_API_BASE.
# Libera apenas a origem de produção; em dev o Vite faz proxy (same-origin).
CORS_ALLOWED_ORIGINS = [
    'https://grupo-orcoma.vercel.app',
]

ROOT_URLCONF = 'orcoma_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orcoma_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# O parâmetro `channel_binding=require` (presente em algumas URLs geradas
# pelo Neon) causa "SSL error: decryption failed or bad record mac" com o
# psycopg2. Removemos automaticamente para evitar o erro, mantendo o restante.
_db_url = (os.environ.get('DATABASE_URL') or '').strip()
_db_url = _db_url.replace('channel_binding=require', '').replace('&&', '&').rstrip('&?')
# Evita o ValueError "No support for ''" quando a DATABASE_URL estiver vazia
# ou for apenas um host sem esquema (falta "postgresql://user:pass@...").
if not _db_url:
    _db_url = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

DATABASES = {
    'default': dj_database_url.parse(
        _db_url,
        conn_max_age=60,
        conn_health_checks=True,
    )
}

# Em desenvolvimento (sem DATABASE_URL) continua usando o SQLite local,
# preservando o ajuste de performance original.
if DATABASES['default']['ENGINE'].endswith('sqlite3'):
    DATABASES['default']['OPTIONS'] = {
        'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
    }


# Custom User Model
AUTH_USER_MODEL = 'core.Usuario'

# Permite login no admin com e-mail ou nome de usuário + senha
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailOuUsuarioBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Diretório onde o `collectstatic` agrega os arquivos para produção
# (WhiteNoise serve a partir daqui no Render). Em dev fica em staticfiles/.
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

# WhiteNoise: serve estáticos comprimidos e com cache em produção.
# Supabase Storage para arquivos de mídia (imagens, PDFs, etc.)
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_KEY = os.environ.get('SUPABASE_KEY', '')
SUPABASE_SERVICE_KEY = os.environ.get('SUPABASE_SERVICE_KEY', '')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'media')

STORAGES = {
    'default': {
        'BACKEND': 'core.storage.SupabaseStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
# Em produção o Render usa um disco persistente (env MEDIA_ROOT=/var/data/media);
# em dev mantém a pasta local media/.
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))


# Frontend build output (Vite)
FRONTEND_DIST_DIR = BASE_DIR.parent / 'frontend' / 'dist'

# WhatsApp Cloud API (Meta) - credenciais vêm do .env, nunca do código
WHATSAPP_TOKEN = os.environ.get('WHATSAPP_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_TEMPLATE_NAME = os.environ.get('WHATSAPP_TEMPLATE_NAME', '')
# Número da Orcoma Comercial no formato internacional, somente dígitos
WHATSAPP_TO = os.environ.get('WHATSAPP_TO', '557399747460')

# Google reCAPTCHA v2 (checkbox) - credenciais vêm do .env, nunca do código
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '')

# ---------------------------------------------------------------------------
# E-mail (alertas de segurança)
# ---------------------------------------------------------------------------
# Deixe EMAIL_HOST em branco para apenas logar os alertas (nada quebra).
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@orcoma.com.br')
# Destinatário dos alertas de segurança detectados pelo site.
ALERT_EMAIL_TO = os.environ.get('ALERT_EMAIL_TO', '')

# URL pública do site (usada nos links dos e-mails de alerta)
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# ---------------------------------------------------------------------------
# CKEditor 5 (editor WYSIWYG dos posts do blog)
# ---------------------------------------------------------------------------
CKEDITOR_5_FILE_UPLOAD_PERMISSION = 'staff'  # apenas usuários staff/painel enviam imagens

CKEDITOR_5_CONFIGS = {
    'extends': {
        'language': 'pt-br',
        'undo': {
            'stackSize': 100,
        },
        'toolbar': {
            'items': [
                'undo', 'redo', '|',
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', 'highlight', 'removeFormat', '|',
                'fontColor', 'fontBackgroundColor', '|',
                'alignment', '|',
                'bulletedList', 'numberedList', 'todoList', '|',
                'link', 'blockQuote', 'codeBlock', '|',
                'insertImage', 'imageUpload', 'insertTable', '|',
                'sourceEditing',
            ],
            'shouldNotGroupWhenFull': True,
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight', 'imageStyle:side', '|',
                'toggleImageCaption', 'imageResize',
            ],
            'styles': ['full', 'side', 'alignLeft', 'alignCenter', 'alignRight', 'block'],
            'resizeOptions': [
                {'name': 'resizeImage:original', 'value': None, 'icon': 'original'},
                {'name': 'resizeImage:25', 'value': '25', 'icon': 'small'},
                {'name': 'resizeImage:50', 'value': '50', 'icon': 'medium'},
                {'name': 'resizeImage:75', 'value': '75', 'icon': 'large'},
            ],
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Parágrafo', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Título 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Título 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Título 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Título 4', 'class': 'ck-heading_heading4'},
                {'model': 'heading5', 'view': 'h5', 'title': 'Título 5', 'class': 'ck-heading_heading5'},
                {'model': 'heading6', 'view': 'h6', 'title': 'Título 6', 'class': 'ck-heading_heading6'},
            ],
        },
        'list': {
            'properties': {
                'styles': 'true',
                'startIndex': 'true',
                'reversed': 'true',
            },
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties',
            ],
        },
    },
}

# ---------------------------------------------------------------------------
# Login / Logout do painel administrativo
# ---------------------------------------------------------------------------
# Após sair do admin ("Sair"), volta direto para a tela de login em vez de
# exibir a página intermediária "Sessão encerrada".
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'
